version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
  - dependency-name: rxjs
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: "@types/pino-http"
    versions:
    - 5.0.6
    - 5.4.0
  - dependency-name: pino-http
    versions:
    - 5.3.0
    - 5.4.0
  - dependency-name: lodash
    versions:
    - 4.17.20
