name: build-lint-test

on:
  workflow_call:

jobs:
  build-lint-test:
    strategy:
      fail-fast: false
      matrix:
        nestjs-version:
          - "8"
          - "9"
          - "10"
          - "11"
        nodejs-version:
          - 20
          - 22
          - 24
        include:
          - nestjs-version: 8
            typescript-version: 4
            reflect-metadata-version: ^0.1.12
          - nestjs-version: 9
            typescript-version: 4
            reflect-metadata-version: ^0.1.12
          - nestjs-version: 10
            typescript-version: 5
            reflect-metadata-version: ^0.2.2
          - nestjs-version: 11
            typescript-version: 5
            reflect-metadata-version: ^0.2.2

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version: ${{ matrix.nodejs-version }}
      - run: npm ci
      - run: |
          npm i @nestjs/core@${{ matrix.nestjs-version }} \
                @nestjs/common@${{ matrix.nestjs-version }} \
                @nestjs/platform-express@${{ matrix.nestjs-version }} \
                @nestjs/platform-fastify@${{ matrix.nestjs-version }} \
                @nestjs/testing@${{ matrix.nestjs-version }} \
                @types/node@${{ matrix.nodejs-version }} \
                typescript@${{ matrix.typescript-version }} \
                reflect-metadata@${{ matrix.reflect-metadata-version }} \
                -D
      - run: npm run lint
      - uses: actions/cache@v4.3.0
        with:
          path: coverage
          key: ${{ github.sha }}-${{ matrix.nestjs-version }}-${{ matrix.nodejs-version }}
      - run: npm t
      - run: npm run build
